services:

  order-service:
    image: 'order-service:4.0'
    container_name: 'order-service'
    ports:
      - "8081:8081"
    environment:
      - EUREKA_SERVER_ADDRESS=http://host.docker.internal:8761/eureka
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OKTA_CLIENT_ID=0oaf1kz9cpI7vpqtl5d7
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OKTA_CLIENT_SECRET=KnWDwRBAzV-OQRRV0072XwNEfaotr_07Evpbs28yK3ul6vdD4Az9__xwd8d9VBxA
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OKTA_ISSUER_URI=https://dev-43724657.okta.com/oauth2/default
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:9296  
      - CONFIG_HOST=config-server:9296
    # command: ["./wait-for-it.sh", "config-server:9296", "--", "java", "-jar", "/order-service/target/order-service-0.0.1-SNAPSHOT.jar"]